osx_image: xcode7.3
language: swift
cache: cocoapods
before_install:
- gem install cocoapods # Since Travis is not always on latest version
- pod repo update --silent
- pod install --project-directory=Example
script:
- set -o pipefail && xcodebuild test -workspace Example/Stylable.xcworkspace -scheme Stylable-Example -sdk iphonesimulator9.3 ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
